version: '3.8'
  
services:
  app:
    image: node:20.19
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: >
      sh -c "
      npm install -g pnpm &&
      pnpm install &&
      pnpm run dev --host"
    ports:
      - 3000:3000